DEVX-2740: Patch Credential Onboarding bug
adobe/aio-lib-console-project-installation pull request #8
Opened 2022-08-19 14:05 UTC by roribio

Patch a bug where service credential on-boarding overwrites previously attached services.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-19 14:11 UTC, roribio commented
Tests passed locally but not in PR. Looking.

2022-08-19 19:16 UTC, AmyJZhao approved these changes

2022-08-22 14:42 UTC, slitviachenko requested changes
@roribio , I left some comments to PR.
Can you please also investigate this behavior? I mean a requirement to specify all services, even the existing ones, and not having a possibility to add just one service. It would be better to discuss this with the Console team as well.

2022-08-22 22:10 UTC, roribio commented on src/TemplateInstallManager.js
>      for (const workspace of currentWorkspaces) {
Fixed ✅

2022-08-22 22:17 UTC, roribio commented on src/TemplateInstallManager.js
> +    const serviceInfo = this.getServicesInfo(orgId, services)
Fixed ✅

2022-08-22 22:17 UTC, roribio commented on src/TemplateInstallManager.js
> +   * @param {Array} services The service to get the info for.
Added to suggestions batch ✅

2022-08-22 22:18 UTC, roribio commented on src/TemplateInstallManager.js
> +    const serviceInfo = services.map(sp => {
Fixed both ✅

2022-08-22 22:24 UTC, roribio commented on src/TemplateInstallManager.js
> +        licenseConfigs: (orgServiceDefinition?.properties?.licenseConfigs || null) && orgServiceDefinition?.properties?.licenseConfigs.map(l => ({
Not sure I agree 🤔

 If  `licenseConfigs` is not defined, then `(orgServiceDefinition?.properties?.licenseConfigs || null)` will evaluate `null` to `true`. If we try to evaluate `orgServiceDefinition?.properties?.licenseConfigs` the second time without `?.`, we don't know which object/key is missing that caused the expression to evaluate to null in the first place and will throw an error.

2022-08-22 22:25 UTC, roribio commented on src/TemplateInstallManager.js
> +          productId: l?.productId
Yes, for whatever reason it's supported 🤷

2022-08-22 22:25 UTC, roribio commented on test/data-mocks.js
> +    // Removed name propoerty to test service mapping when service definition has no name
Added to suggestion batch. ✅

2022-08-22 23:20 UTC, roribio commented on src/TemplateInstallManager.js
> +        await this.onboardEnterpriseApi(orgId, projectId, workspaceId, enterpriseServices)
Fixed! ✅ The assertion I added is for ten (10) calls since there are 5 workspaces configured in the `data-mocks.js` file.

2022-08-23 15:22 UTC, slitviachenko commented on src/TemplateInstallManager.js
> +        licenseConfigs: (orgServiceDefinition?.properties?.licenseConfigs || null) && orgServiceDefinition?.properties?.licenseConfigs.map(l => ({
Not sure I got your message.
> If licenseConfigs is not defined, then (orgServiceDefinition?.properties?.licenseConfigs || null) will evaluate null to true.
```
console.log(undefined || null)
null
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND
> More generally, the operator returns the value of the first [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) operand encountered when evaluating from left to right, or the value of the last operand if they are all [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).

2022-08-23 16:08 UTC, slitviachenko requested changes
@roribio , I re-reviewed the PR, left some comments

2022-08-23 16:41 UTC, roribio commented on README.md
> +const templateManager = await templateHandler.init(accessToken, appConfigFile, templateName, installConfigFile)
Ah, good catch. I copied my `README.md` changes from `DEVX-2401`

2022-08-23 16:42 UTC, roribio commented on src/TemplateInstallManager.js
> +        licenseConfigs: (orgServiceDefinition?.properties?.licenseConfigs || null) && orgServiceDefinition?.properties?.licenseConfigs.map(l => ({
Interesting 🤔 I didn't know that. Thanks 👍

2022-08-23 16:44 UTC, roribio commented on README.md
> +const templateManager = await templateHandler.init(accessToken, appConfigFile, templateName, installConfigFile)
Fixed ✅

2022-08-23 16:45 UTC, roribio commented on src/TemplateInstallManager.js
> +        licenseConfigs: (orgServiceDefinition?.properties?.licenseConfigs || null) && orgServiceDefinition?.properties?.licenseConfigs.map(l => ({
Fixed ✅

2022-08-23 17:58 UTC, slitviachenko commented on src/TemplateInstallManager.js
> +    const servicesInfo = this.getServicesInfo(orgId, services)
```suggestion
    const servicesInfo = await this.getServicesInfo(orgId, services)
```

2022-08-23 17:58 UTC, slitviachenko commented on src/TemplateInstallManager.js
> +    const servicesInfo = this.getServicesInfo(orgId, services)
```suggestion
    const servicesInfo = await this.getServicesInfo(orgId, services)
```

2022-08-23 20:16 UTC, roribio commented on src/TemplateInstallManager.js
> +    const servicesInfo = this.getServicesInfo(orgId, services)
Fixed :white_check_mark:

2022-08-23 20:16 UTC, roribio commented on src/TemplateInstallManager.js
> +    const servicesInfo = this.getServicesInfo(orgId, services)
Fixed :white_check_mark:

2022-08-23 20:36 UTC, roribio commented on test/TemplateInstallManager.test.js
>      await expect(templateManager.installTemplate('343284', '4566206088344794932')).resolves.toBeUndefined()
Fixed ✅

2022-08-23 21:27 UTC, slitviachenko approved these changes

2022-08-23 21:36 UTC, AmyJZhao approved these changes

2022-08-23 21:38 UTC, merged